#+title: Chapter 2
#+date: <2025-07-30 Wed 20:56>
#+startup: latexpreview
#+startup: overview

* 2.1
** Notes

*** In deriving equation (2.4), the fundamental theorem of calculus is

\begin{equation*}
\int\limits^b_a\frac{df(t)}{dt}dt = f(b) - f(a)
\end{equation*}

** Exercises

*** 1.


\begin{equation*}
q(x,t) = -\kappa\frac{\partial u}{\partial x}(x, t)
\end{equation*}


Heat flux, $q$, has units of energy per unit area per unit time. In SI units, this is Joules per square meter per second $\left(J/m^2s\right)$.

\begin{equation*}
\left[q\right] = \frac{\mathrm{J}}{\mathrm{m^2s}}
\end{equation*}

Temperature, $u$, is in $K$.

\begin{equation*}
\left[\frac{\partial u}{\partial x}\right] = \frac{\mathrm{K}}{\mathrm{m}}
\end{equation*}

Therefore, the thermal conductivity $\kappa$ is in units of Joules seconds per meter per Kelvin, or Watts per meter per Kelvin.

\begin{equation*}
\left[\kappa\right] = \mathrm{\frac{J}{smK}} = \mathrm{\frac{W}{mK}}
\end{equation*}

*** 3.

Equation (2.1) is


\begin{equation*}
E_0 + \int\limits^{x + \Delta x}_x A \rho c (u(s, t) - T_0)ds
\end{equation*}

In the integral,
  - $A$ has units of meters squared,
  - $\rho$ has units of kilograms per cubic meter,
  - $c$ has units of Joules per kilogram per Kelvin,
  - $u$ and $T$ both have using of Kelvin,
  - and $ds$ has units of meters.


\begin{equation*}
\left[A\rho c (u(s, t) - T_0) ds\right] = m^2\frac{kg}{m^3}\frac{J}{kg\cdot K} K m = J
\end{equation*}

*** 5.

\begin{equation*}
\left[r\right] = \frac{J}{s}
\end{equation*}

The heat flux $q$ can be related to $r$ by $q(l, t) = -r/A$. The negative sign is due to the negative orientation of the heat source.

Therefore, $q(l,t) = -\kappa\frac{\partial u}{\partial x}(l, t) = -\frac{r}{A}$.

The boundary condition at $x=l$ is then

\begin{equation*}
\frac{\partial u}{\partial x}(l, t) = \frac{1}{\kappa}\frac{r}{A}
\end{equation*}

*** 7.

$\kappa = 0.802\,\frac{\mathrm{W}}{\mathrm{cm K}}$
$l = 1\,\mathrm{m}$
$r = 1\,\mathrm{cm}$
Lateral boundary completely insulated -> no loss along the bar
$u(0,t) = 20^{\circ}\,\mathrm{C}$
$u(l,t) = 30^{\circ}\,\mathrm{C}$

**** (a)


\begin{equation*}
\begin{aligned}
-\kappa\frac{d^2u}{dx^2} & = 0,\quad 0 < x < l \\
u(0) & = 20^{\circ}\,\nomath{C} \\
u(100) & = 30^{\circ}\,\nomath{C}
\end{aligned}
\end{equation*}

From Example 2.2:


\begin{equation*}
u(x) = 20 + \frac{x}{10}
\end{equation*}

**** (b)

\begin{equation*}
q(x, t) = -\kappa \frac{\partial u}{\partial x}(x, t)
\end{equation*}


\begin{equation*}
\frac{\partial u}{\partial x} = \frac{1}{10}
\end{equation*}


\begin{equation*}
q = -\kappa\frac{\partial u}{\partial x} = -\frac{0.802}{10} = -0.0802\, \frac{\mathrm{W}}{\mathrm{cm}^2}
\end{equation*}

Heat flux is given by $Aq$.

\begin{equation*}
Aq = (1\,\mathrm{cm})^2\pi\left(-0.0802\,\frac{\mathrm{W}}{\mathrm{cm^2}}\right) = 0.252\,\mathrm{W}
\end{equation*}

*** 9.

Newton's law of cooling

\begin{equation*}
q(x, t) = \alpha\Delta u
\end{equation*}

where $\alpha$ is a constant of proportionality and $\Delta u = u_{\mathrm{bar}} - u_{\mathrm{medium}}$.

Fourier's law of heat conduction

\begin{equation*}
q(x, t) = -\kappa \frac{\partial u_{\mathrm{bar}}}{\partial x}(x, t)
\end{equation*}

\begin{equation*}
\alpha\Delta u = \alpha u_{\mathrm{bar}} - \alpha u_{\mathrm{medium}} = -\kappa\frac{\partial u}{\partial x}
\end{equation*}

The boundary condition is

\begin{equation*}
u_{\mathrm{bar}} + \frac{\kappa}{\alpha}\frac{\partial u_\mathrm{bar}}{\partial x} = u_{\mathrm{medium}}
\end{equation*}

*** 11


\begin{equation*}
\frac{\partial u}{\partial t} - D\frac{\partial^2 u}{\partial x^2} = f(x, t)
\end{equation*}

Both ends of the pipe are sealed, so diffusive transport will not occur through the ends of the pipe. Since the rate of diffusion is proportional to the concentration gradient, the concentration gradient is equal to zero.

\begin{equation*}
\frac{\partial u}{\partial x}(x, t) = 0
\end{equation*}

for $x = 0$ and $x = l$.

For initial conditions, the concentration must be defined at all points within the pipe at the initial time.


\begin{equation*}
u(x, t_0) = \psi(x), \quad 0 < x < l
\end{equation*}

The complete IBVP is

\begin{equation*}
\begin{align}
\frac{\partial u}{\partial t} - D\frac{\partial^2 u}{\partial x^2} & = f(x, t),\quad 0 < x < l,\, t > t_0, \\
u(x, t_0) & = \psi(x), \quad 0<x<l, \\
\frac{\partial u}{\partial x}(0, t) & = 0,\quad t > t_0, \\
\frac{\partial u}{\partial x}(l, t) & = 0,\quad t > t_0.
\end{align}
\end{equation*}

*** 13

- $l$ - length of pipe
- $r$ - radius of pipe
- $u_0$ - concentration of left reservoir
- $u_l$ - concentration of right reservoir

$u(0,t) = u_0$ and $u(l,t) = u_l$

**** (a)

The steady state problem is


\begin{equation*}
\begin{align}
-D\frac{d^2 u}{d x^2} & = 0,\quad 0 < x < l, \\
u(0) & = u_0, \\
u(l) & = u_l.
\end{align}
\end{equation*}

Integrating once yields

\begin{equation*}
\frac{d u}{d x} = C_1.
\end{equation*}

Integrating a second time yields

\begin{equation*}
u = C_1 x + C_2.
\end{equation*}

Solving for $u(0) = u_0$,

\begin{equation*}
u(0) = C_2 = u_0.
\end{equation*}

Now solving for $u(l) = u_l$:

\begin{equation*}
\begin{align}
u(l) & = C_1 l + u_0 = u_l \\
\Rightarrow C_1 & = \frac{u_l - u_0}{l}
\end{align}
\end{equation*}

Therefore

\begin{equation*}
u(x) = \frac{u_l - u_0}{l}x + u_0.
\end{equation*}

The rate at which a chemical moves across a cross section is

\begin{equation*}
-D\frac{\partial u}{\partial t}(x, t),
\end{equation*}

therefore the rate at which the mass diffuses is

\begin{equation*}
\begin{aligned}
-AD\frac{\partial u}{\partial t}(x, t) & = -AD\frac{u_l - u_0}{l} \\
& = -\pi r^2 D \frac{u_l - u_0}{l}
\end{aligned}
\end{equation*}

**** (b)

The rate increases as $r$ increases and decreases as $l$ increases.

* 2.2

** DONE Exercises [4/4]

*** DONE 1.
CLOSED: [2025-08-06 Wed 07:42]

The internal force at the end of the bar is

\begin{equation*}
-Ak(l)\frac{du}{dx}(l).
\end{equation*}

The force at the end of the bar is equal to

\begin{equation*}
F = pA,
\end{equation*}

where $p$ is the applied pressure and $A$ is the area of the end of the bar. Since the bar is not accelerating, the sum of forces is equal to zero.


\begin{equation*}
-Ak(l)\frac{du}{dx}(l) + pA = 0.
\end{equation*}

Solving for $\frac{du}{dx}(l)$,


\begin{equation*}
\frac{du}{dx}(l) = \frac{p}{k}.
\end{equation*}

Therefore, the boundary conditions are

\begin{equation*}
\begin{align}
u(0) & = 0 \\
\frac{du}{dx}(l) & = \frac{p}{k(l)}
\end{align}
\end{equation*}

*** DONE 3.
CLOSED: [2025-08-06 Wed 19:58]

$k = 195\,\mathrm{GPa}$

$1\,\mathrm{Pa} = 1\,\mathrm{\frac{N}{m^2}}$

$1\,\mathrm{N} = 1\,\mathrm{kg\cdot\frac{m}{s^2}}$

**** (a)

Internal force at a cross section along the bar is

$F = Ak\frac{du}{dx}$

Dividing by area gives pressure

$p = \frac{F}{A} = k\frac{du}{dx}$

Therefore


\begin{equation*}
k = \frac{p}{\frac{du}{dx}}.
\end{equation*}

If the bar is length $l$, since $k=195\,\mathrm{GPa}$, it takes $195A\,\mathrm{GN}$ to stretch the bar to $(1+\epsilon)l$, where $\epsilon$ is the fractional increase in the length of the bar.

**** (b)

$k=195\,\mathrm{GPa}$, $p = 1\,\mathrm{GPa}$, $l=1\,\mathrm{m}$, $r=1\,\mathrm{cm}$

\begin{equation*}
\begin{align}
p & = k\frac{du}{dx} \\
\Rightarrow \frac{du}{dx} & = \frac{p}{k} = \frac{1\,\mathrm{GPa}}{195\,\mathrm{GPa}} = 5.13\times10^{-3}
\end{align}
\end{equation*}

The length after the equilibrium state is reached:

\begin{equation*}
(1+\epsilon)l = (1+5.13\times10^{-3})(1\,\mathrm{m}) = 1.005\,\mathrm{m}
\end{equation*}

The new length is $1.005\,\mathrm{m}$.

**** (c)

The BVP is


\begin{equation*}
\begin{align}
-k\frac{d^2u}{dx^2} & = 0, \\
u(0) & = 0, \\
\frac{du}{dx}(l) & = \frac{p}{k}
\end{align}
\end{equation*}

Integrating the differential equation twice yields


\begin{equation*}
u(x) = C_2x + C_1
\end{equation*}

Using the first boundary condition

$u(0) = C_1 = 0$

Applying the second boundary condition,

$\frac{du}{dx} = C_2 = \frac{p}{k}$

The solution is then

\begin{equation*}
u = \frac{p}{k}x
\end{equation*}

Solving for $x=l$,

\begin{equation*}
u = \frac{1\,\mathrm{GPa}}{195\,\mathrm{GPa}}(1\,\mathrm{m}) = 5.13\times10^{-3}\,\mathrm{m}
\end{equation*}

The total length after equilibrium is reached is

\begin{equation*}
l = 1.005\,\mathrm{m}
\end{equation*}

*** DONE 5.
CLOSED: [2025-08-07 Thu 08:21]

$\rho = 7.9\,\mathrm{\frac{g}{cm^3}}$

The wave equation, in general, is


\begin{equation*}
\rho\frac{\partial^2 u}{\partial t^2} - \frac{\partial}{\partial x}\left(k(x)\frac{\partial u}{\partial x}\right) = f(x,t)
\end{equation*}

Since, in this case, $\frac{\partial k}{\partial x} = 0$,

\begin{equation*}
\rho\frac{\partial^2 u}{\partial t^2} - k\frac{\partial^2 u}{\partial x^2} = f(x,t).
\end{equation*}

The wave equation will be written in SI units.

From problem 3, $k=195\,\mathrm{GPa}=195\times 10^9\,\mathrm{Pa} = 1.95\times 10^{11}\,\mathrm{Pa}$.

The density is


\begin{equation*}
\begin{align}
\rho & = 7.9\,\mathrm{\frac{g}{cm^3}} \times \mathrm{\frac{\left(100\,cm\right)^3}{\left(1\,m\right)^3}} \times \mathrm{\frac{1\,kg}{1\times 10^3 g}}\\
& = 7.9\times 10^3\,\mathrm{\frac{kg}{m^3}}
\end{align}
\end{equation*}

The wave equation for the bar is then,

\begin{equation*}
\left(7.9\times 10^3\,\mathrm{\frac{kg}{m^3}}\right)\frac{\partial^2 u}{\partial t^2} -
   \left(1.95\times 10^{11} \mathrm{Pa}\right)\frac{\partial^2 u}{\partial x^2} = f(x,t)
\end{equation*}

$\frac{\partial^2 u}{\partial t^2}$ has units of $\mathrm{\frac{m}{s^2}}$. Therefore, the units of the first term are

\begin{equation*}
\mathrm{\frac{kg}{m^2}\times\frac{m}{s^2} = \frac{N}{m^3}.
\end{equation*}

In the second term, $\frac{\partial^2 u}{\partial x^2}$ has units of $\mathrm{\frac{1}{m}}$. Therefore, the units of the second term are

\begin{equation*}
\mathrm{Pa \times \frac{1}{m} = \frac{N}{m^3}}.
\end{equation*}

$f(x,t)$ must also have units of Newtons per meter cubed, or Newtons per cubic meter.

\begin{equation*}
\left[f(x,t)\right] = \mathrm{\frac{N}{m^3}}
\end{equation*}

*** DONE 7.
CLOSED: [2025-08-07 Thu 20:08]

**** (a)

Show that

\begin{equation*}
u(x,t) = \cos(c\theta t)\sin(\theta x)
\end{equation*}

is a solution to

\begin{equation*}
\frac{\partial^2 u}{\partial t^2} - c^2\frac{\partial^2 u}{\partial x^2} = 0,\,0<x<l\quad\text{for all t}.
\end{equation*}

Finding the partial derivatives of $u$:


\begin{equation*}
\begin{align}
\frac{\partial u}{\partial t} & = -c\theta\sin(c\theta t)\sin(\theta x) \\
\frac{\partial^2 u}{\partial t^2} & = -c^2\theta^2\cos(c\theta t)\sin(\theta x)
\end{align}
\end{equation*}

\begin{equation*}
\begin{align}
\frac{\partial u}{\partial x} & = \theta\cos(c\theta t)\cos(\theta x) \\
\frac{\partial^2 u}{\partial x^2} & = -\theta^2\cos(c\theta t)\sin(\theta x)
\end{align}
\end{equation*}

Substituting into the PDE yields


\begin{equation*}
\begin{align}
\frac{\partial^2 u}{\partial t^2} - c^2\frac{\partial^2 u}{\partial x^2} =
-c^2\theta^2\cos(c\theta t)\sin(\theta x) + c^2\theta^2\cos(c\theta t)\sin(\theta x) = 0
\end{align}
\end{equation*}

Therefore, $u$ is a solution.

**** (b)

Dirichlet conditions are

\begin{equation*}
\begin{align}
u(0, t) & = 0 \\
u(l, t) & = 0
\end{align}
\end{equation*}

for all t.

\begin{equation*}
u(x,t) = \cos(c\theta t)\sin(\theta x)
\end{equation*}

For $x=0$,

\begin{equation*}
u(0,t) = \cos(c\theta t)\sin(\theta 0) = 0
\end{equation*}

Any value of $\theta$ works here since $\sin(\theta 0) = 0$ for all $\theta$ and all $t$.

For $x = l$,


\begin{equation*}
u(l,t) = \cos(c\theta t)\sin(\theta l) = 0
\end{equation*}

$u=0$ when $\sin(\theta l) = 0$, which occurs when $\theta l = 0, \pm\pi, \pm2\pi, \dots, \pmn\pi$, so

\begin{equation*}
\theta = \frac{n\pi}{l},\,n=0,\pm1,\pm2,\dots.
\end{equation*}
